// Diseño factorial fraccional (Run, BR, AMF, FVF, SFL, AFL, T)
// '+' = 1, '-' = -1, '0' = 0 (centro), null = (no usado en esa fila / sin signo)
// Basado en la imagen adjunta del usuario.

window.FACTORIAL_DESIGN = [
  // Bloque 1-16: half-fraction factorial
  { run: 1,  BR:'-', AMF:'-', FVF:'-', SFL:'-', AFL:'-', T:'-' },
  { run: 2,  BR:'+', AMF:'-', FVF:'-', SFL:'-', AFL:'-', T:'+' },
  { run: 3,  BR:'-', AMF:'+', FVF:'-', SFL:'-', AFL:'-', T:'+' },
  { run: 4,  BR:'+', AMF:'+', FVF:'-', SFL:'-', AFL:'-', T:'-' },
  { run: 5,  BR:'-', AMF:'-', FVF:'+', SFL:'-', AFL:'-', T:'+' },
  { run: 6,  BR:'+', AMF:'-', FVF:'+', SFL:'-', AFL:'-', T:'-' },
  { run: 7,  BR:'-', AMF:'+', FVF:'+', SFL:'-', AFL:'-', T:'-' },
  { run: 8,  BR:'+', AMF:'+', FVF:'+', SFL:'-', AFL:'-', T:'+' },
  { run: 9,  BR:'-', AMF:'-', FVF:'-', SFL:'+', AFL:'-', T:'+' },
  { run: 10, BR:'+', AMF:'-', FVF:'-', SFL:'+', AFL:'-', T:'-' },
  { run: 11, BR:'-', AMF:'+', FVF:'-', SFL:'+', AFL:'-', T:'-' },
  { run: 12, BR:'+', AMF:'+', FVF:'-', SFL:'+', AFL:'-', T:'+' },
  { run: 13, BR:'-', AMF:'-', FVF:'+', SFL:'+', AFL:'-', T:'-' },
  { run: 14, BR:'+', AMF:'-', FVF:'+', SFL:'+', AFL:'-', T:'+' },
  { run: 15, BR:'-', AMF:'+', FVF:'+', SFL:'+', AFL:'-', T:'+' },
  { run: 16, BR:'+', AMF:'+', FVF:'+', SFL:'+', AFL:'-', T:'-' },
  { run: 17, BR:'-', AMF:'-', FVF:'-', SFL:'-', AFL:'+', T:'+' },
  { run: 18, BR:'+', AMF:'-', FVF:'-', SFL:'-', AFL:'+', T:'-' },
  { run: 19, BR:'-', AMF:'+', FVF:'-', SFL:'-', AFL:'+', T:'-' },
  { run: 20, BR:'+', AMF:'+', FVF:'-', SFL:'-', AFL:'+', T:'+' },
  { run: 21, BR:'-', AMF:'-', FVF:'+', SFL:'-', AFL:'+', T:'-' },
  { run: 22, BR:'+', AMF:'-', FVF:'+', SFL:'-', AFL:'+', T:'+' },
  { run: 23, BR:'-', AMF:'+', FVF:'+', SFL:'-', AFL:'+', T:'+' },
  { run: 24, BR:'+', AMF:'+', FVF:'+', SFL:'-', AFL:'+', T:'-' },
  { run: 25, BR:'-', AMF:'-', FVF:'-', SFL:'+', AFL:'+', T:'-' },
  { run: 26, BR:'+', AMF:'-', FVF:'-', SFL:'+', AFL:'+', T:'+' },
  { run: 27, BR:'-', AMF:'+', FVF:'-', SFL:'+', AFL:'+', T:'+' },
  { run: 28, BR:'+', AMF:'+', FVF:'-', SFL:'+', AFL:'+', T:'-' },
  { run: 29, BR:'-', AMF:'-', FVF:'+', SFL:'+', AFL:'+', T:'+' },
  { run: 30, BR:'+', AMF:'-', FVF:'+', SFL:'+', AFL:'+', T:'-' },
  { run: 31, BR:'-', AMF:'+', FVF:'+', SFL:'+', AFL:'+', T:'-' },
  { run: 32, BR:'+', AMF:'+', FVF:'+', SFL:'+', AFL:'+', T:'+' },
  // Star points (33-44)
  { run: 33, BR:'-', AMF:'0', FVF:'0', SFL:'0', AFL:'0', T:'0' },
  { run: 34, BR:'+', AMF:'0', FVF:'0', SFL:'0', AFL:'0', T:'0' },
  { run: 35, BR:'0', AMF:'-', FVF:'0', SFL:'0', AFL:'0', T:'0' },
  { run: 36, BR:'0', AMF:'+', FVF:'0', SFL:'0', AFL:'0', T:'0' },
  { run: 37, BR:'0', AMF:'0', FVF:'-', SFL:'0', AFL:'0', T:'0' },
  { run: 38, BR:'0', AMF:'0', FVF:'+', SFL:'0', AFL:'0', T:'0' },
  { run: 39, BR:'0', AMF:'0', FVF:'0', SFL:'-', AFL:'0', T:'0' },
  { run: 40, BR:'0', AMF:'0', FVF:'0', SFL:'+', AFL:'0', T:'0' },
  { run: 41, BR:'0', AMF:'0', FVF:'0', SFL:'0', AFL:'-', T:'0' },
  { run: 42, BR:'0', AMF:'0', FVF:'0', SFL:'0', AFL:'+', T:'0' },
  { run: 43, BR:'0', AMF:'0', FVF:'0', SFL:'0', AFL:'0', T:'-' },
  { run: 44, BR:'0', AMF:'0', FVF:'0', SFL:'0', AFL:'0', T:'+' },
  // Centro (45) - 3 réplicas internas
  { run: 45, BR:'0', AMF:'0', FVF:'0', SFL:'0', AFL:'0', T:'0' },
];

window.I18N = {
  es: {
    title: 'Resultados de Ensayos',
    subtitle: 'Diseño factorial · 45 mezclas · Retracción / Flexión / Compresión',
    progress: 'Progreso',
    overall: 'Avance global',
    mix: 'Mezcla',
    mixes: 'Mezclas',
    factors: 'Factores del diseño',
    showDesign: 'Mostrar diseño factorial',
    hideDesign: 'Ocultar diseño factorial',
    age: 'Edad',
    ages: 'Edades',
    days: 'días',
    day: 'día',
    test: 'Ensayo',
    tests: 'Ensayos',
    retraction: 'Retracción',
    flexion: 'Flexión',
    compression: 'Compresión',
    replicas: 'Réplicas',
    replica: 'Réplica',
    upload: 'Subir archivo',
    uploadFile: 'Cargar archivo .txt',
    dropHere: 'Arrastra el .txt o haz clic',
    castDate: 'Fecha de fundido',
    testDate: 'Fecha de ensayo',
    length: 'Largo (mm)',
    height: 'Alto (mm)',
    width: 'Ancho (mm)',
    weight: 'Peso (g)',
    pmax: 'P máx (kN)',
    smax: 'σ máx (MPa)',
    notes: 'Observaciones',
    pending: 'Pendiente',
    inProgress: 'En curso',
    done: 'Completo',
    avg: 'Promedio',
    sd: 'Desv.',
    cv: 'CV',
    points: 'puntos',
    curve: 'Curva',
    load: 'Carga (kN)',
    disp: 'Despl. (mm)',
    stress: 'Tensión (MPa)',
    strain: 'Deformación',
    summary: 'Resumen',
    backToList: '← Volver',
    centerN45: 'Punto central (3 réplicas)',
    starPoint: 'Punto estrella',
    factorialPoint: 'Vértice factorial',
    delete: 'Eliminar',
    save: 'Guardar',
    cancel: 'Cancelar',
    edit: 'Editar',
    parsed: 'Procesado',
    noFile: 'Sin archivo',
    file: 'Archivo',
    selectMix: 'Selecciona una mezcla',
    legend: 'Leyenda',
    high: 'Alto (+1)',
    low: 'Bajo (−1)',
    center: 'Centro (0)',
    factor_BR: 'BR',
    factor_AMF: 'AMF',
    factor_FVF: 'FVF',
    factor_SFL: 'SFL',
    factor_AFL: 'AFL',
    factor_T: 'T',
    nReplicas: 'réplicas',
    summaryStats: 'Estadísticas',
    of: 'de',
    completed: 'completos',
    noData: 'Sin datos',
    metadata: 'Metadatos',
    drop: 'Soltar aquí',
    parsing: 'Procesando…',
    parseError: 'Error al procesar',
    confirmDelete: '¿Eliminar este archivo y resultados?',
    shrinkageValue: 'Retracción (μm/m)',
    shrinkageHint: 'Ingrese valor de retracción medido',
    gridTitle: 'Selecciona una mezcla',
    specimen: 'Probeta',
    specimens: 'Probetas',
    measurements: 'mediciones',
    atAge: 'a',
    expandAll: 'Ver 12 mediciones',
    collapse: 'Colapsar',
    addAge: 'Añadir edad',
    viewCurve: 'Ver curva',
    welcome: 'Bienvenido',
    pickUserDesc: 'Elige el usuario con el que vas a trabajar.',
    allMixes: 'Todas las mezclas',
    allTests: 'Todos los ensayos',
    allAges: 'Todas las edades',
    onlyWithData: 'Con datos',
    params: 'Parámetros',
    clear: 'Limpiar',
    unsavedSwitch: 'Tienes cambios sin guardar. ¿Cambiar de usuario igualmente?',
    bulkCorrectConfirm: '¿Aplicar corrección automática a TODAS las probetas de flexión que aún no tengan corrección? (Requiere haber llegado a 1 kN)',
    bulkCorrect: 'Corregir flexión (todas)',
    exportExcel: 'Exportar',
    exportModalTitle: 'Elegir variables a exportar',
    exportModalHint: 'Se exportan 2 hojas (Compresión y Flexión), una fila por mezcla (N45 en 3 réplicas), con las variables marcadas para cada probeta/edad.',
    selectAll: 'Marcar todas',
    selectNone: 'Desmarcar todas',
    viewerTab: 'Visualizador',
    quickUpload: 'Carga rápida',
    analysisTab: 'Análisis',
    viewerPickHint: 'Selecciona un ensayo desde Mezclas → click en una probeta o Retracción.',
    openComparator: 'Abrir comparador de curvas',
    comparatorHint: 'Superpone y compara varias curvas en una ventana.',
    viewerEmpty: 'Sin datos cargados',
    autoCorrectFail: 'No se pudo corregir automáticamente: la probeta no alcanzó 1 kN, o no se hallaron los puntos de referencia (0.4 / 0.8 kN).',
    setOrigin: 'Fijar inicio',
    setEnd: 'Fijar fin',
    setFirstPeak: 'Primer peak',
    correctCurve: 'Corregir curva',
    autoCorrectHint: 'Corrección automática: recta entre el punto más cercano a 0.4 kN y el más cercano a 0.8 kN (primer cruce). Solo si la probeta alcanzó 1 kN.',
    autoCorrect: 'Corrección automática',
    reset: 'Resetear',
    addToCompare: 'Comparar',
    hintTrim: 'Click en el punto que será el nuevo origen (t=0, P=0, disp=0).',
    hintTrimEnd: 'Click en el último punto a conservar.',
    hintPeak: 'Click en el primer peak de la curva.',
    firstPeak: 'Primer peak',
    trimmed: 'Recorte',
    shrinkNeedsBase: 'Falta ingresar el día 0 (base) en al menos una probeta.',
    shrinkChangePct: 'Cambio Δ (%)',
    shrinkChange: 'Cambio Δ (μm/m)',
    shrinkBaselineHint: 'Día 0 = base. Curva = lectura − base.',
    timeDays: 'Tiempo (días)',
    values: 'Valores',
    comparator: 'Comparador',
    addCurve: 'Añadir curva',
    clearAllHint: 'Quita todas las curvas del comparador (no borra sus modificaciones)',
    clearAll: 'Quitar todas',
    stateLabel: 'Estado',
    statePure: 'Puro',
    stateProcessed: 'Procesado',
    stateCorrected: 'Corregido',
    ghostHint: 'Dibuja las curvas crudas originales como boceto claro detrás',
    showGhost: 'Boceto de corrección',
    axisLabel: 'Ejes',
    axisAuto: 'Auto',
    axisManual: 'Manual',
    fontSizes: 'Tamaño de letra',
    fontTitles: 'Títulos',
    fontAxes: 'Ejes',
    fontLegend: 'Leyenda',
    axisGap: 'Separación núm.–eje',
    connecting: 'conectando…',
    saving: 'Guardando…',
    unsaved: 'sin guardar',
    savedAt: 'Guardado',
    connected: 'Conectado',
    bulkCorrectTitle: 'Aplica la corrección automática (0.4/0.8 kN) a todas las probetas de flexión que aún no tengan corrección',
    migrateCloud: 'Compactar nube',
    migrateCloudTitle: 'Reescribe todas las mezclas en la nube al nuevo formato compacto (no requiere re-subir archivos)',
    exportExcelTitle: 'Descarga un Excel eligiendo qué variables incluir',
    encodeBy: 'Codificar por factor',
    colorByLabel: 'Color',
    lineByLabel: 'Línea',
    encNone: '— (continua)',
    editColor: 'Editar color',
    compareMixedWarn: 'Estás mezclando ensayos mecánicos y de retracción: los ejes pueden no ser comparables.',
    curves: 'Curvas',
    compareEmpty: 'Añade curvas para comparar.',
    pickCurve: 'Seleccionar ensayos',
    selectedCount: 'seleccionados',
    selectVisible: 'Todos visibles',
    addSelected: 'Añadir',
    search: 'Buscar…',
    aggAll: 'Promedio + individual',
    aggAvg: 'Solo promedio',
    aggInd: 'Solo individual',
    noCurves: 'No hay ensayos.',
    pickAnalysisPoints: 'Seleccionar puntos',
    aggAllAnalysis: 'Individual + Promedio + Ratio',
    aggRatio: 'Solo ratio',
    pickMixes: 'Añadir mezclas (1 punto por mezcla)',
    mixPickerHint: 'Cada mezcla marcada se agrega como un solo punto. El ensayo (compresión/flexión) y la edad se eligen por eje, arriba del gráfico — pueden mezclarse entre el eje X y el eje Y.',
    axisAgeHint: 'Edad fija para este eje (ignora la edad del punto)',
    axisAgeItem: 'Edad del punto',
    fixed: 'fijo',
    axisTestHint: 'Ensayo usado para este eje (compresión o flexión)',
    analysisTitle: 'Análisis de variables',
    addMixPoint: 'Añadir mezclas',
    addPoint: 'Añadir puntos',
    xAxis: 'Eje X',
    yAxis: 'Eje Y',
    pointsWithData: 'puntos con datos válidos para los ejes elegidos',
    analysisEmpty: 'Añade puntos para analizar.',
    errIncomplete: 'Faltan campos. Completa la asignación.',
    confirmClearQueue: '¿Descartar la cola actual?',
    quickUploadDesc: 'Arrastra varios archivos .txt y la app intentará asignarlos automáticamente. Confirma uno por uno.',
    dropFiles: 'Arrastra archivos .txt aquí',
    orClick: 'o haz click para seleccionar',
    files: 'archivos',
    addMore: 'Más archivos',
    queueDone: 'Cola completada.',
    confirmed: 'Confirmado',
    skipped: 'Saltado',
    autoDetected: 'Detección automática:',
    couldNotDetect: 'No se pudo detectar automáticamente. Completa:',
    willOverwrite: 'Esta probeta ya tiene un archivo cargado. Confirmar reemplazará los datos existentes.',
    skip: 'Saltar',
    confirmNext: 'Confirmar y siguiente',
  },
  en: {
    title: 'Test Results',
    subtitle: 'Factorial design · 45 mixes · Shrinkage / Flexure / Compression',
    progress: 'Progress',
    overall: 'Overall progress',
    mix: 'Mix',
    mixes: 'Mixes',
    factors: 'Design factors',
    showDesign: 'Show factorial design',
    hideDesign: 'Hide factorial design',
    age: 'Age',
    ages: 'Ages',
    days: 'days',
    day: 'day',
    test: 'Test',
    tests: 'Tests',
    retraction: 'Shrinkage',
    flexion: 'Flexure',
    compression: 'Compression',
    replicas: 'Replicates',
    replica: 'Replicate',
    upload: 'Upload file',
    uploadFile: 'Upload .txt file',
    dropHere: 'Drop .txt here or click',
    castDate: 'Cast date',
    testDate: 'Test date',
    length: 'Length (mm)',
    height: 'Height (mm)',
    width: 'Width (mm)',
    weight: 'Weight (g)',
    pmax: 'P max (kN)',
    smax: 'σ max (MPa)',
    notes: 'Notes',
    pending: 'Pending',
    inProgress: 'In progress',
    done: 'Done',
    avg: 'Avg',
    sd: 'SD',
    cv: 'CV',
    points: 'points',
    curve: 'Curve',
    load: 'Load (kN)',
    disp: 'Disp. (mm)',
    stress: 'Stress (MPa)',
    strain: 'Strain',
    summary: 'Summary',
    backToList: '← Back',
    centerN45: 'Center point (3 replicates)',
    starPoint: 'Star point',
    factorialPoint: 'Factorial vertex',
    delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    parsed: 'Parsed',
    noFile: 'No file',
    file: 'File',
    selectMix: 'Select a mix',
    legend: 'Legend',
    high: 'High (+1)',
    low: 'Low (−1)',
    center: 'Center (0)',
    factor_BR: 'BR',
    factor_AMF: 'AMF',
    factor_FVF: 'FVF',
    factor_SFL: 'SFL',
    factor_AFL: 'AFL',
    factor_T: 'T',
    nReplicas: 'replicates',
    summaryStats: 'Statistics',
    of: 'of',
    completed: 'completed',
    noData: 'No data',
    metadata: 'Metadata',
    drop: 'Drop here',
    parsing: 'Parsing…',
    parseError: 'Parsing error',
    confirmDelete: 'Delete this file and results?',
    shrinkageValue: 'Shrinkage (μm/m)',
    shrinkageHint: 'Enter measured shrinkage value',
    gridTitle: 'Select a mix',
    specimen: 'Specimen',
    specimens: 'Specimens',
    measurements: 'measurements',
    atAge: 'at',
    expandAll: 'Show 12 readings',
    collapse: 'Collapse',
    addAge: 'Add age',
    viewCurve: 'View curve',
    welcome: 'Welcome',
    pickUserDesc: 'Choose the user you\'ll be working as.',
    allMixes: 'All mixes',
    allTests: 'All tests',
    allAges: 'All ages',
    onlyWithData: 'With data',
    params: 'Parameters',
    clear: 'Clear',
    unsavedSwitch: 'You have unsaved changes. Switch user anyway?',
    bulkCorrectConfirm: 'Apply automatic correction to ALL flexure specimens that don\'t have one yet? (Requires reaching 1 kN)',
    bulkCorrect: 'Correct flexure (all)',
    exportExcel: 'Export',
    exportModalTitle: 'Choose variables to export',
    exportModalHint: 'Exports 2 sheets (Compression and Flexure), one row per mix (N45 as 3 replicates), with the checked variables for each specimen/age.',
    selectAll: 'Select all',
    selectNone: 'Deselect all',
    viewerTab: 'Viewer',
    quickUpload: 'Quick upload',
    analysisTab: 'Analysis',
    viewerPickHint: 'Select a test from Mixes → click a specimen or Shrinkage.',
    openComparator: 'Open curve comparator',
    comparatorHint: 'Overlay and compare several curves in one window.',
    viewerEmpty: 'No data loaded',
    autoCorrectFail: 'Automatic correction failed: the specimen didn\'t reach 1 kN, or the reference points (0.4 / 0.8 kN) weren\'t found.',
    setOrigin: 'Set start',
    setEnd: 'Set end',
    setFirstPeak: 'First peak',
    correctCurve: 'Correct curve',
    autoCorrectHint: 'Automatic correction: line between the point nearest 0.4 kN and the one nearest 0.8 kN (first crossing). Only if the specimen reached 1 kN.',
    autoCorrect: 'Auto correction',
    reset: 'Reset',
    addToCompare: 'Compare',
    hintTrim: 'Click the point that will become the new origin (t=0, P=0, disp=0).',
    hintTrimEnd: 'Click the last point to keep.',
    hintPeak: 'Click the first peak of the curve.',
    firstPeak: 'First peak',
    trimmed: 'Trim',
    shrinkNeedsBase: 'The day-0 baseline is missing on at least one specimen.',
    shrinkChangePct: 'Change Δ (%)',
    shrinkChange: 'Change Δ (μm/m)',
    shrinkBaselineHint: 'Day 0 = baseline. Curve = reading − baseline.',
    timeDays: 'Time (days)',
    values: 'Values',
    comparator: 'Comparator',
    addCurve: 'Add curve',
    clearAllHint: 'Removes all curves from the comparator (does not delete their edits)',
    clearAll: 'Remove all',
    stateLabel: 'State',
    statePure: 'Raw',
    stateProcessed: 'Processed',
    stateCorrected: 'Corrected',
    ghostHint: 'Draws the original raw curves as a faint sketch behind',
    showGhost: 'Correction sketch',
    axisLabel: 'Axes',
    axisAuto: 'Auto',
    axisManual: 'Manual',
    fontSizes: 'Font size',
    fontTitles: 'Titles',
    fontAxes: 'Axes',
    fontLegend: 'Legend',
    axisGap: 'Number–axis gap',
    connecting: 'connecting…',
    saving: 'Saving…',
    unsaved: 'unsaved',
    savedAt: 'Saved',
    connected: 'Connected',
    bulkCorrectTitle: 'Applies the automatic correction (0.4/0.8 kN) to all flexure specimens that don\'t have one yet',
    migrateCloud: 'Compact cloud',
    migrateCloudTitle: 'Rewrites all mixes in the cloud to the new compact format (no need to re-upload files)',
    exportExcelTitle: 'Download an Excel choosing which variables to include',
    encodeBy: 'Encode by factor',
    colorByLabel: 'Color',
    lineByLabel: 'Line',
    encNone: '— (solid)',
    editColor: 'Edit color',
    compareMixedWarn: 'You\'re mixing mechanical and shrinkage tests: the axes may not be comparable.',
    curves: 'Curves',
    compareEmpty: 'Add curves to compare.',
    pickCurve: 'Select tests',
    selectedCount: 'selected',
    selectVisible: 'All visible',
    addSelected: 'Add',
    search: 'Search…',
    aggAll: 'Average + individual',
    aggAvg: 'Average only',
    aggInd: 'Individual only',
    noCurves: 'No tests.',
    pickAnalysisPoints: 'Select points',
    aggAllAnalysis: 'Individual + Average + Ratio',
    aggRatio: 'Ratio only',
    pickMixes: 'Add mixes (1 point per mix)',
    mixPickerHint: 'Each checked mix is added as a single point. The test (compression/flexure) and age are chosen per axis, above the chart — they can differ between the X and Y axes.',
    axisAgeHint: 'Fixed age for this axis (ignores the point\'s age)',
    axisAgeItem: 'Point\'s age',
    fixed: 'fixed',
    axisTestHint: 'Test used for this axis (compression or flexure)',
    analysisTitle: 'Variable analysis',
    addMixPoint: 'Add mixes',
    addPoint: 'Add points',
    xAxis: 'X axis',
    yAxis: 'Y axis',
    pointsWithData: 'points with valid data for the chosen axes',
    analysisEmpty: 'Add points to analyze.',
    errIncomplete: 'Missing fields. Complete the assignment.',
    confirmClearQueue: 'Discard the current queue?',
    quickUploadDesc: 'Drag several .txt files and the app will try to assign them automatically. Confirm one by one.',
    dropFiles: 'Drop .txt files here',
    orClick: 'or click to select',
    files: 'files',
    addMore: 'More files',
    queueDone: 'Queue completed.',
    confirmed: 'Confirmed',
    skipped: 'Skipped',
    autoDetected: 'Auto-detected:',
    couldNotDetect: 'Couldn\'t auto-detect. Fill in:',
    willOverwrite: 'This specimen already has a file loaded. Confirming will overwrite the existing data.',
    skip: 'Skip',
    confirmNext: 'Confirm and next',
  }
};
