// Diseño factorial fraccional (Run, BR, AMF, FVF, SFL, AFL, T)
// '+' = 1, '-' = -1, '0' = 0 (centro), null = (no usado en esa fila / sin signo)
// Basado en la imagen adjunta del usuario.

window.FACTORIAL_DESIGN = [
  // Bloque 1-16: half-fraction factorial
  { run: 1,  BR:'-', AMF:'-', FVF:'-', SFL:'-', AFL:'-', T:'-' },
  { run: 2,  BR:'+', AMF:'-', FVF:'-', SFL:'-', AFL:'-', T:'+' },
  { run: 3,  BR:'-', AMF:'+', FVF:'-', SFL:'-', AFL:'-', T:'+' },
  { run: 4,  BR:'+', AMF:'+', FVF:'-', SFL:'-', AFL:'-', T:'-' },
  { run: 5,  BR:'-', AMF:'-', FVF:'+', SFL:'-', AFL:'-', T:'+' },
  { run: 6,  BR:'+', AMF:'-', FVF:'+', SFL:'-', AFL:'-', T:'-' },
  { run: 7,  BR:'-', AMF:'+', FVF:'+', SFL:'-', AFL:'-', T:'-' },
  { run: 8,  BR:'+', AMF:'+', FVF:'+', SFL:'-', AFL:'-', T:'+' },
  { run: 9,  BR:'-', AMF:'-', FVF:'-', SFL:'+', AFL:'-', T:'+' },
  { run: 10, BR:'+', AMF:'-', FVF:'-', SFL:'+', AFL:'-', T:'-' },
  { run: 11, BR:'-', AMF:'+', FVF:'-', SFL:'+', AFL:'-', T:'-' },
  { run: 12, BR:'+', AMF:'+', FVF:'-', SFL:'+', AFL:'-', T:'+' },
  { run: 13, BR:'-', AMF:'-', FVF:'+', SFL:'+', AFL:'-', T:'-' },
  { run: 14, BR:'+', AMF:'-', FVF:'+', SFL:'+', AFL:'-', T:'+' },
  { run: 15, BR:'-', AMF:'+', FVF:'+', SFL:'+', AFL:'-', T:'+' },
  { run: 16, BR:'+', AMF:'+', FVF:'+', SFL:'+', AFL:'-', T:'-' },
  { run: 17, BR:'-', AMF:'-', FVF:'-', SFL:'-', AFL:'+', T:'+' },
  { run: 18, BR:'+', AMF:'-', FVF:'-', SFL:'-', AFL:'+', T:'-' },
  { run: 19, BR:'-', AMF:'+', FVF:'-', SFL:'-', AFL:'+', T:'-' },
  { run: 20, BR:'+', AMF:'+', FVF:'-', SFL:'-', AFL:'+', T:'+' },
  { run: 21, BR:'-', AMF:'-', FVF:'+', SFL:'-', AFL:'+', T:'-' },
  { run: 22, BR:'+', AMF:'-', FVF:'+', SFL:'-', AFL:'+', T:'+' },
  { run: 23, BR:'-', AMF:'+', FVF:'+', SFL:'-', AFL:'+', T:'+' },
  { run: 24, BR:'+', AMF:'+', FVF:'+', SFL:'-', AFL:'+', T:'-' },
  { run: 25, BR:'-', AMF:'-', FVF:'-', SFL:'+', AFL:'+', T:'-' },
  { run: 26, BR:'+', AMF:'-', FVF:'-', SFL:'+', AFL:'+', T:'+' },
  { run: 27, BR:'-', AMF:'+', FVF:'-', SFL:'+', AFL:'+', T:'+' },
  { run: 28, BR:'+', AMF:'+', FVF:'-', SFL:'+', AFL:'+', T:'-' },
  { run: 29, BR:'-', AMF:'-', FVF:'+', SFL:'+', AFL:'+', T:'+' },
  { run: 30, BR:'+', AMF:'-', FVF:'+', SFL:'+', AFL:'+', T:'-' },
  { run: 31, BR:'-', AMF:'+', FVF:'+', SFL:'+', AFL:'+', T:'-' },
  { run: 32, BR:'+', AMF:'+', FVF:'+', SFL:'+', AFL:'+', T:'+' },
  // Star points (33-44)
  { run: 33, BR:'-', AMF:'0', FVF:'0', SFL:'0', AFL:'0', T:'0' },
  { run: 34, BR:'+', AMF:'0', FVF:'0', SFL:'0', AFL:'0', T:'0' },
  { run: 35, BR:'0', AMF:'-', FVF:'0', SFL:'0', AFL:'0', T:'0' },
  { run: 36, BR:'0', AMF:'+', FVF:'0', SFL:'0', AFL:'0', T:'0' },
  { run: 37, BR:'0', AMF:'0', FVF:'-', SFL:'0', AFL:'0', T:'0' },
  { run: 38, BR:'0', AMF:'0', FVF:'+', SFL:'0', AFL:'0', T:'0' },
  { run: 39, BR:'0', AMF:'0', FVF:'0', SFL:'-', AFL:'0', T:'0' },
  { run: 40, BR:'0', AMF:'0', FVF:'0', SFL:'+', AFL:'0', T:'0' },
  { run: 41, BR:'0', AMF:'0', FVF:'0', SFL:'0', AFL:'-', T:'0' },
  { run: 42, BR:'0', AMF:'0', FVF:'0', SFL:'0', AFL:'+', T:'0' },
  { run: 43, BR:'0', AMF:'0', FVF:'0', SFL:'0', AFL:'0', T:'-' },
  { run: 44, BR:'0', AMF:'0', FVF:'0', SFL:'0', AFL:'0', T:'+' },
  // Centro (45) - 3 réplicas internas
  { run: 45, BR:'0', AMF:'0', FVF:'0', SFL:'0', AFL:'0', T:'0' },
];

window.I18N = {
  es: {
    title: 'Resultados de Ensayos',
    subtitle: 'Diseño factorial · 45 mezclas · Retracción / Flexión / Compresión',
    progress: 'Progreso',
    overall: 'Avance global',
    mix: 'Mezcla',
    mixes: 'Mezclas',
    factors: 'Factores del diseño',
    showDesign: 'Mostrar diseño factorial',
    hideDesign: 'Ocultar diseño factorial',
    age: 'Edad',
    ages: 'Edades',
    days: 'días',
    day: 'día',
    test: 'Ensayo',
    tests: 'Ensayos',
    retraction: 'Retracción',
    flexion: 'Flexión',
    compression: 'Compresión',
    replicas: 'Réplicas',
    replica: 'Réplica',
    upload: 'Subir archivo',
    uploadFile: 'Cargar archivo .txt',
    dropHere: 'Arrastra el .txt o haz clic',
    castDate: 'Fecha de fundido',
    testDate: 'Fecha de ensayo',
    length: 'Largo (mm)',
    height: 'Alto (mm)',
    width: 'Ancho (mm)',
    weight: 'Peso (g)',
    pmax: 'P máx (kN)',
    smax: 'σ máx (MPa)',
    notes: 'Observaciones',
    pending: 'Pendiente',
    inProgress: 'En curso',
    done: 'Completo',
    avg: 'Promedio',
    sd: 'Desv.',
    cv: 'CV',
    points: 'puntos',
    curve: 'Curva',
    load: 'Carga (kN)',
    disp: 'Despl. (mm)',
    stress: 'Tensión (MPa)',
    strain: 'Deformación',
    summary: 'Resumen',
    backToList: '← Volver',
    centerN45: 'Punto central (3 réplicas)',
    starPoint: 'Punto estrella',
    factorialPoint: 'Vértice factorial',
    delete: 'Eliminar',
    save: 'Guardar',
    cancel: 'Cancelar',
    edit: 'Editar',
    parsed: 'Procesado',
    noFile: 'Sin archivo',
    file: 'Archivo',
    selectMix: 'Selecciona una mezcla',
    legend: 'Leyenda',
    high: 'Alto (+1)',
    low: 'Bajo (−1)',
    center: 'Centro (0)',
    factor_BR: 'BR',
    factor_AMF: 'AMF',
    factor_FVF: 'FVF',
    factor_SFL: 'SFL',
    factor_AFL: 'AFL',
    factor_T: 'T',
    nReplicas: 'réplicas',
    summaryStats: 'Estadísticas',
    of: 'de',
    completed: 'completos',
    noData: 'Sin datos',
    metadata: 'Metadatos',
    drop: 'Soltar aquí',
    parsing: 'Procesando…',
    parseError: 'Error al procesar',
    confirmDelete: '¿Eliminar este archivo y resultados?',
    shrinkageValue: 'Retracción (μm/m)',
    shrinkageHint: 'Ingrese valor de retracción medido',
    gridTitle: 'Selecciona una mezcla',
    specimen: 'Probeta',
    specimens: 'Probetas',
    measurements: 'mediciones',
    atAge: 'a',
    expandAll: 'Ver 12 mediciones',
    collapse: 'Colapsar',
  },
  en: {
    title: 'Test Results',
    subtitle: 'Factorial design · 45 mixes · Shrinkage / Flexure / Compression',
    progress: 'Progress',
    overall: 'Overall progress',
    mix: 'Mix',
    mixes: 'Mixes',
    factors: 'Design factors',
    showDesign: 'Show factorial design',
    hideDesign: 'Hide factorial design',
    age: 'Age',
    ages: 'Ages',
    days: 'days',
    day: 'day',
    test: 'Test',
    tests: 'Tests',
    retraction: 'Shrinkage',
    flexion: 'Flexure',
    compression: 'Compression',
    replicas: 'Replicates',
    replica: 'Replicate',
    upload: 'Upload file',
    uploadFile: 'Upload .txt file',
    dropHere: 'Drop .txt here or click',
    castDate: 'Cast date',
    testDate: 'Test date',
    length: 'Length (mm)',
    height: 'Height (mm)',
    width: 'Width (mm)',
    weight: 'Weight (g)',
    pmax: 'P max (kN)',
    smax: 'σ max (MPa)',
    notes: 'Notes',
    pending: 'Pending',
    inProgress: 'In progress',
    done: 'Done',
    avg: 'Avg',
    sd: 'SD',
    cv: 'CV',
    points: 'points',
    curve: 'Curve',
    load: 'Load (kN)',
    disp: 'Disp. (mm)',
    stress: 'Stress (MPa)',
    strain: 'Strain',
    summary: 'Summary',
    backToList: '← Back',
    centerN45: 'Center point (3 replicates)',
    starPoint: 'Star point',
    factorialPoint: 'Factorial vertex',
    delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    parsed: 'Parsed',
    noFile: 'No file',
    file: 'File',
    selectMix: 'Select a mix',
    legend: 'Legend',
    high: 'High (+1)',
    low: 'Low (−1)',
    center: 'Center (0)',
    factor_BR: 'BR',
    factor_AMF: 'AMF',
    factor_FVF: 'FVF',
    factor_SFL: 'SFL',
    factor_AFL: 'AFL',
    factor_T: 'T',
    nReplicas: 'replicates',
    summaryStats: 'Statistics',
    of: 'of',
    completed: 'completed',
    noData: 'No data',
    metadata: 'Metadata',
    drop: 'Drop here',
    parsing: 'Parsing…',
    parseError: 'Parsing error',
    confirmDelete: 'Delete this file and results?',
    shrinkageValue: 'Shrinkage (μm/m)',
    shrinkageHint: 'Enter measured shrinkage value',
    gridTitle: 'Select a mix',
    specimen: 'Specimen',
    specimens: 'Specimens',
    measurements: 'measurements',
    atAge: 'at',
    expandAll: 'Show 12 readings',
    collapse: 'Collapse',
  },
  it: {
    title: 'Risultati delle Prove',
    subtitle: 'Disegno fattoriale · 45 miscele · Ritiro / Flessione / Compressione',
    progress: 'Progresso',
    overall: 'Avanzamento globale',
    mix: 'Miscela',
    mixes: 'Miscele',
    factors: 'Fattori del disegno',
    showDesign: 'Mostra disegno fattoriale',
    hideDesign: 'Nascondi disegno fattoriale',
    age: 'Età',
    ages: 'Età',
    days: 'giorni',
    day: 'giorno',
    test: 'Prova',
    tests: 'Prove',
    retraction: 'Ritiro',
    flexion: 'Flessione',
    compression: 'Compressione',
    replicas: 'Repliche',
    replica: 'Replica',
    upload: 'Carica file',
    uploadFile: 'Carica file .txt',
    dropHere: 'Trascina .txt o clicca',
    castDate: 'Data di getto',
    testDate: 'Data della prova',
    length: 'Lunghezza (mm)',
    height: 'Altezza (mm)',
    width: 'Larghezza (mm)',
    weight: 'Peso (g)',
    pmax: 'P max (kN)',
    smax: 'σ max (MPa)',
    notes: 'Note',
    pending: 'In attesa',
    inProgress: 'In corso',
    done: 'Completo',
    avg: 'Media',
    sd: 'Dev.',
    cv: 'CV',
    points: 'punti',
    curve: 'Curva',
    load: 'Carico (kN)',
    disp: 'Spost. (mm)',
    stress: 'Tensione (MPa)',
    strain: 'Deformazione',
    summary: 'Riepilogo',
    backToList: '← Indietro',
    centerN45: 'Punto centrale (3 repliche)',
    starPoint: 'Punto stella',
    factorialPoint: 'Vertice fattoriale',
    delete: 'Elimina',
    save: 'Salva',
    cancel: 'Annulla',
    edit: 'Modifica',
    parsed: 'Elaborato',
    noFile: 'Nessun file',
    file: 'File',
    selectMix: 'Seleziona una miscela',
    legend: 'Legenda',
    high: 'Alto (+1)',
    low: 'Basso (−1)',
    center: 'Centro (0)',
    factor_BR: 'BR',
    factor_AMF: 'AMF',
    factor_FVF: 'FVF',
    factor_SFL: 'SFL',
    factor_AFL: 'AFL',
    factor_T: 'T',
    nReplicas: 'repliche',
    summaryStats: 'Statistiche',
    of: 'di',
    completed: 'completate',
    noData: 'Nessun dato',
    metadata: 'Metadati',
    drop: 'Rilascia qui',
    parsing: 'Elaborazione…',
    parseError: 'Errore di elaborazione',
    confirmDelete: 'Eliminare questo file e i risultati?',
    shrinkageValue: 'Ritiro (μm/m)',
    shrinkageHint: 'Inserire valore di ritiro misurato',
    gridTitle: 'Seleziona una miscela',
    specimen: 'Provino',
    specimens: 'Provini',
    measurements: 'misurazioni',
    atAge: 'a',
    expandAll: 'Mostra 12 misurazioni',
    collapse: 'Comprimi',
  }
};
